Decision\DecisionBundle\Entity\AttributesRegular:
    type: entity
    table: null
    repositoryClass: Decision\DecisionBundle\Entity\AttributesRegularRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
        player:
            targetEntity: Player
            inversedBy: attributesRegular
            joinColumn:
                name: player_id
                referenceColumnName: id
    fields:
        strength:
            type: string
            length: 50
        reactions:
            type: string
            length: 50
        height:
            type: integer
        accuracy:
            type: string
            length: 50
        injuries:
            type: integer
        age:
            type: integer
    lifecycleCallbacks: {  }
