Decision\DecisionBundle\Entity\AttributesNormalized:
    type: entity
    table: null
    repositoryClass: Decision\DecisionBundle\Entity\AttributesNormalizedRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
        player:
            targetEntity: Player
            inversedBy: attributesNormalized
            joinColumn:
                name: player_id
                referenceColumnName: id
    fields:
        strength:
            type: integer
        reactions:
            type: integer
        height:
            type: integer
        accuracy:
            type: integer
        injuries:
            type: integer
        age:
            type: integer
    lifecycleCallbacks: {  }
