Decision\DecisionBundle\Entity\Team:
    type: entity
    table: null
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: teamName
    repositoryClass: Decision\DecisionBundle\Entity\TeamRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        team_players:
            nullable: true
            targetEntity: Player
            mappedBy: playerTeamId
    manyToOne:
        teamUserId:
            nullable: true
            targetEntity: User
            inversedby: userTeams
            joinColumn:
                name: team_user_id
                referencedColumnName: id
    fields:
        teamName:
            type: string
            length: 60
            column: team_name
            unique: true
        teamAssisted:
            type: boolean
            column: team_assisted
    lifecycleCallbacks: {  }
