<?php

namespace Decision\DecisionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AttributesNormalizedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributesNormalizedRepository extends EntityRepository
{
}
