decision_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: DecisionBundle:Default:index }

decision_fetch:
    pattern: /show
    defaults: { _controller: DecisionBundle:Default:show }

team_add:
    pattern: /team/add
    defaults: { _controller: DecisionBundle:Team:addTeam }

team_add_players:
    pattern: /team/add_players/{team_id}
    defaults: { _controller: DecisionBundle:Team:addPlayers }

player_add:
    pattern: /player/add
    defaults: { _controller: DecisionBundle:Player:addPlayer }

player_add_attrib:
    pattern: /player/add_attrib/{player_id}
    defaults: { _controller: DecisionBundle:Player:addAttrib }

player_add_success:
    pattern: /player/success/{player_id}
    defaults: { _controller: DecisionBundle:Player:addSuccess }

team_add_player:
    pattern: /player/add_to_team/{team_id}/{player_id}
    defaults: { _controller: DecisionBundle:Team:addPlayer }

team_remove_player:
    pattern: /player/remove_from_team/{team_id}/{player_id}
    defaults: { _controller: DecisionBundle:Team:removePlayer }

team_list:
    pattern: /team/list
    defaults: { _controller: DecisionBundle:Team:listTeams }

team_list_players:
    pattern: /team/list_players/{team_id}
    defaults: { _controller: DecisionBundle:Team:listPlayers }