decision_homepage:
    pattern:  /
    defaults: { _controller: DecisionBundle:Default:index }

decision_fetch:
    pattern: /show
    defaults: { _controller: DecisionBundle:Default:show }

player_add:
    pattern: /player/add
    defaults: { _controller: DecisionBundle:Player:addPlayer }

player_add_attrib:
    pattern: /player/add_attrib/{player_id}
    defaults: { _controller: DecisionBundle:Player:addAttrib }

player_add_success:
    pattern: /player/success/{player_id}
    defaults: { _controller: DecisionBundle:Player:addSuccess }

player_remove:
    pattern: /player/remove/{player_id}
    defaults: { _controller: DecisionBundle:Player:deletePlayer }

player_generate_random:
    pattern: /player/generate_random/{counter}
    defaults: { _controller: DecisionBundle:Player:randomGenerate }

player_list_all:
    pattern: /player/list/all
    defaults: { _controller: DecisionBundle:Player:listAll }

team_add_player:
    pattern: /player/add_to_team/{team_id}/{player_id}
    defaults: { _controller: DecisionBundle:Team:addPlayer }

team_remove_player:
    pattern: /player/remove_from_team/{team_id}/{player_id}
    defaults: { _controller: DecisionBundle:Team:removePlayer }

team_list:
    pattern: /team/list
    defaults: { _controller: DecisionBundle:Team:listTeams }

team_list_players:
    pattern: /team/list_players/{team_id}
    defaults: { _controller: DecisionBundle:Team:listPlayers }

team_add:
    pattern: /team/add
    defaults: { _controller: DecisionBundle:Team:addTeam }

team_add_players:
    pattern: /team/add_players/{team_id}
    defaults: { _controller: DecisionBundle:Team:addPlayers }

team_delete:
    pattern: /team/delete/{team_id}
    defaults: { _controller: DecisionBundle:Team:delete }